### ISSUE TITLE
Side chains / Plasma

### ISSUE THREAD

**Issue by youarentryan** [ConsenSysLabs/ethereum-developer-tools-list#1]
Should probably capture some of the core projects building reusable state channels, plasma, and side chain components:
- Side chains: Loom
- State channels: Spankchain
- Plasma: OmiseGo

**Comment by pakaplace** [comment]
Thanks @youarentryan, I'll add it. I think you have edit access to the readme.md if you want to go ahead and add it next time.

**Comment by rstormsf** [comment]
Side chain: https://poa.net/
Sidechain  contracts, deployment books, Dapps and whole bunch of other goodies:
- https://github.com/poanetwork

Interoperability: POA bridge: http://bridge.poa.net/
- https://github.com/poanetwork/poa-bridge
- https://github.com/poanetwork/bridge-ui
- https://github.com/poanetwork/poa-bridge-contracts

Ethereum client exthereum is now called Mana: 
- https://github.com/poanetwork/mana

Open Sourced Ethereum explorer: 
- https://github.com/poanetwork/poa-explorer

**Comment by pakaplace** [comment]
@rstormsf added, thanks!
